config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :show, :edit, :destroy, :update, :index] do
    resources :comments, only: [:create, :destroy] do
      resources :favorites, only: [:create, :destroy]
      # favoriteの対象がcommentの時は特定のcommentのidが必要なのでbooksにネストする
    end
    resources :favorites, only: [:create, :destroy]
    # favoriteの対象がbookの時は特定のbookのidが必要なのでbooksにネストする
  end
  resources :users, only: [:show, :index, :edit, :update] do
    get :favorited_book_list, on: :member
    get :favorited_comment_list, on: :member
    resource :relationships, only: [:create, :destroy]
    # 1ユーザーに対してつけられるフォローは１なのでrelationshipの特定のためのidを持たせる必要はなく、resouceでOK
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' =>'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    # その本のIDを含むfavoritesのレコードに、引数のユーザーのレコードがあるか？
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment, optional: true
  belongs_to :book, optional: true
  # いいねの対象がどっちか一方の為、optional: trueでnilを許すようにする
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_comments, through: :favorites, source: :comment
  # favoriteテーブルにあるuser_idはcomment/book2種類あるので、sourceの指定でどっちの情報を引っ張ってくるのか指定する
  has_many :favorited_books, through: :favorites, source: :book
  has_many :follower, class_name:"Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローする立場、follower_idとしてrelationshipテーブルに自分のidを複数持つ（中間テーブルとの関係）
  has_many :followed, class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローされる立場、followed_IDとしてrelationshipテーブルに自分のidを複数持つ（中間テーブルとの関係）
  has_many :following_users, through: :follower, source: :followed
  # 自分がフォローする立場(follower)、Relationshipのfollowerを通してfollowed(user)からfollowing_usersを持っている
  has_many :follower_users, through: :followed, source: :follower
  # 自分がフォローされる立場(followed)、Relationshipのfollowedを通してfollower(user)からfollower_usersを持っている

  def follow(user_id)
    self.follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    self.follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    self.following_users.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end
  
  def after_sign_in_path_for(resource)
    # sign_in後のパス指定（デフォルトでroot_path）
    user_path(resource)
    # user#showにsign-inで受け取ったresource(user)の情報を渡している
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  
  def index
    @books = Book.all
  end
  
  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to user_path(current_user)
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :opinion)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to request.referer
    end
  end

  def destroy
    if Comment.find(params[:id]).destroy
      redirect_to request.referer
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(book_id: params[:book_id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
 def create
  if params[:comment_id]
    current_user.favorites.create(comment_id: params[:comment_id])
  elsif params[:book_id]
    current_user.favorites.create(book_id: params[:book_id])
  end
  redirect_to request.referer
 end
 
 def destroy
   if params[:comment_id]
     current_user.favorites.find_by(comment_id: params[:comment_id]).destroy
   elsif params[:book_id]
     current_user.favorites.find_by(book_id: params[:book_id]).destroy
   end
   redirect_to request.referer
 end
 
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    @user = User.find(params[:user_id])
    @followings = @user.following_users
  end

  def followers
    @user = User.find(params[:user_id])
    @followers = @user.follower_users
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def index
    @users = User.all
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    end
  end

  def favorited_book_list
    @user = User.find(params[:id])
    @favorited_books = @user.favorited_books
  end
  
  def favorited_comment_list
    @user = User.find(params[:id])
    @favorited_comments = @user.favorited_comments
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_list.html.erb
<table class="table">
  <thead>
    <tr>
      <td></td>
      <td>Title</td>
      <td>Opinion</td>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size:"40x40" %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book) do %>
            <%= book.title %>
          <% end %>
        </td>
        <td><%= book.opinion %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <h2>Editting Book</h2>
      <%= form_with model: @book, local: true do |f| %>
      <div class="field">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :opinion, "Opinion" %>
        <%= f.text_area :opinion %>
      </div>
      <%= f.submit "Update Book", class:"btn btn-succecc" %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: "users/sidebar", locals: { user: current_user, book: Book.new} %>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <%= render partial: "books/book_list", locals: {books: @books} %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: "users/sidebar", locals: { user: @book.user, book: Book.new } %>
    </div>
    <div class="col-xs-9">
      <h2>Book Detail</h2>
      <table class="table">
        <tr>
          <td><%= attachment_image_tag @book.user, :profile_image, size:"40x40",fallback:"no_image.jpg", size:"40x40" %></td>
          <td><%= @book.title %></td>
          <td><%= @book.opinion %></td>
          <td>
            <%= link_to edit_book_path(@book) do %>
              <button class="btn btn-success">Edit</button>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book), method: :delete, data: {confirm: "削除しますか？"} do %>
              <button class="btn btn-danger">Delete</button>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="comment-form">
        <%= render partial: "comments/comment_form", locals: { book: @book, comment: @comment } %>
      </div>
      <% if @book.comments.any? %>
        <div class="comment-index">
          <h3>コメント一覧</h3>
          <%= render partial: "comments/comment_index", locals: { comments: @book.comments } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<%= form_with model:[book, comment], local: true do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class:"form-control",placeholder:"コメントをここに" %>
  </div>
  <%= f.submit "送信する", class:"btn btn-primary pull-right" %>
<% end %>

app/views/comments/_comment_index.html.erb
<table class="table">
  <% comments.each do |comment| %>
    <tr>
      <td><%= attachment_image_tag comment.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %></td>
      <td><%= comment.content %></td>
      <td>いいね<%= comment.favorites.count %>件
        <% if comment.favorited_by?(current_user) %>
          <%= link_to "いいねを取り消す", book_comment_favorite_path(book_id: comment.book.id, comment_id: comment.id), method: :delete %>
        <% else %>
          <%= link_to "いいねする", book_comment_favorites_path(book_id: comment.book.id, comment_id: comment.id), method: :post %>
        <% end %>
      </td>
      <td>
        <% if comment.user == current_user %>
          <%= link_to book_comment_path(comment.book, comment), method: :delete do %>
            <button class="btn btn-danger">削除</button>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers22</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <%= link_to "ホーム", user_path(current_user) %>
        <%= link_to "BOOKS", books_path %>
        <%= link_to "USERS", users_path %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/relationships/followers.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <% if @followers.count == 0 %>
        <h2>フォロワーはいません</h2>
      <% else %>
        <h2><%= @user.name %>さんのフォロワー一覧</h2>
        <table class="table">
          <thead>
            <tr>
              <td>image</td>
              <td>name</td>
              <td>フォロー数</td>
              <td>フォロワー数</td>
              <td></td>
            </tr>
          </thead>
          <tbody>
            <% @followers.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size:"40x40" %>
                </td>
                <td><%= user.name %></td>
                <td>
                  <%= link_to user.following_users.count, user_followings_path(user) %>
                </td>
                <td>
                  <%= link_to user.follower_users.count, user_followers_path(user) %>
                </td>
                <td>
                  <%= link_to "show", user_path(user) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <% if @followings.count == 0 %>
        <h2>フォローしていません</h2>
      <% else %>
        <h2><%= @user.name %>さんのフォロー一覧</h2>
        <table class="table">
          <thead>
            <tr>
              <td>image</td>
              <td>name</td>
              <td>フォロー数</td>
              <td>フォロワー数</td>
              <td></td>
            </tr>
          </thead>
          <tbody>
            <% @followings.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size:"40x40" %>
                </td>
                <td><%= user.name %></td>
                <td>
                  <%= link_to user.following_users.count, user_followings_path(user) %>
                </td>
                <td>
                  <%= link_to user.follower_users.count, user_followers_path(user) %>
                </td>
                <td>
                  <%= link_to "show", user_path(user) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <h2>User info</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= attachment_image_tag user, :profile_image, size: "80x80", fallback: "no_image.jpg", size: "80x80" %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table">
        <tr>
          <td>name</td>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <td>introduction</td>
          <td><%= user.introduction %></td>
        </tr>
        <tr>
          <td>
            <%= link_to "follows", user_followings_path(user) %>
          </td>
          <td><%= user.following_users.count %></td>
        </tr>
        <tr>
          <td>
            <%= link_to "followers", user_followers_path(user) %>
          </td>
          <td><%= user.follower_users.count %></td>
        </tr>
        <% if user.id == current_user.id %>
          <tr>
            <td>
              <%= link_to "いいね投稿", favorited_book_list_user_path(user) %>
            </td>
            <td><%= user.favorited_books.count %></td>
          </tr>
          <tr>
            <td>
              <%= link_to "いいねコメント", favorited_comment_list_user_path(user) %>
            </td>
            <td><%= user.favorited_comments.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <% if current_user == user %>
    <div class="row">
      <div class="col-xs-12">
        <%= link_to edit_user_path(user) do %>
          <button>プロフィール設定</button>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-xs-12">
    <h2>New book</h2>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <%= form_with model: book, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %><br>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :opinion, "Opinion" %><br>
        <%= f.text_area :opinion, class: "form-control" %>
      </div>
      <%= f.submit "Create Book", class:"btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6">
      <h2>User info</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, autofocus: true%>
        </div>
        <div class="field">
          <%= f.label :profile_image %><br>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="field">
          <%= f.label :introduction %><br>
          <%= f.text_area :introduction %>
        </div>
        <%= f.submit "Update User" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorited_book_list.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: "users/sidebar", locals: {user: @user, book: Book.new} %>
    </div>
    <div class="col-xs-9">
      <h2>Favorited Books</h2>
      <%= render partial: "books/book_list", locals: {books: @favorited_books} %>
    </div>
  </div>
</div>

app/views/users/favorited_comment_list.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: "users/sidebar", locals: { user: @user, book: Book.new} %>
    </div>
    <div class="col-xs-9">
      <h2>Your Favorited Comments</h2>
      <%= render partial: "comments/comment_index", locals: {comments: @favorited_comments } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: "users/sidebar", locals: { user: current_user, book: Book.new } %>
    </div>
    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <td>image</td>
            <td>name</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size:"40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "show", user_path(user) %></td>
              <td>フォロー数：<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
              <td>
                <% if current_user != user %>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationships_path(user), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: 'users/sidebar', locals: {user: @user, book: @book }%>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <td></td>
            <td>Title</td>
            <td>Opinion</td>
            <td></td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= attachment_image_tag book.user, :profile_image, size:"40x40", fallback: "no_image.jpg", size:"40x40" %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.opinion %></td>
              <td>コメント数：<%= book.comments.count %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to "いいねを取り消す", book_favorite_path(book), method: :delete %>
                <% else %>
                  <%= link_to "いいねする", book_favorites_path(book), method: :post %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>